### ISSUE TITLE
Optionally allocate idle costs

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-model#103]
There are a number of reasons why a user may want to allocate idle resources back to individual pods, namespaces, etc. I see two potential approaches for accomplishing this:

1) allocating costs based on limits -- this would require teams/owners to set resource limits.

2) allocating idle cluster costs -- this could be done uniformly or proportionately based on pod consumption.

I'm starting this issue to discuss these two approaches and/or others. Whatever approach we take, I believe we should give users the ability to enable/disable this feature.

**Comment by AjayTripathy** [comment]
I'm not sure allocating costs by limit is necessarily the same as leaving something idle. Kubernetes will run pods on a node whose resource limits sum to something greater than the node will provide: see the description of "overcommitted state"[https://cloud.google.com/blog/products/gcp/kubernetes-best-practices-resource-requests-and-limits](here) .

**Comment by jspriesterbach-5thkind** [comment]
We are trying to get the cost per namespace where we are reserving for example 5gb of memory and 2cpu cores for a one pod, 1gb of memory and .5 cpu for another, etc. We want to see the entire cost of those pods running on our nodes, with the idle time included. 

We have a cluster of nodes with multiple clients/namespaces running on them. We need to be able to charge each client/namespace for the time their pods are using on our servers, not just the resources the particular pods may consume, because we keep extra idle cpu time available for some pods that have to burst when a job comes in.

**Comment by dwbrown2** [comment]
This is now underway and is targeted for our next weekly release.

**Comment by dwbrown2** [comment]
Released in v1.31
