### ISSUE TITLE
automated repair of CUR Athena table

### ISSUE THREAD

**Issue by kirbsauce** [kubecost/cost-model#1045]
If the CUR is setup outside of CloudFormation, the necessary components to periodically repair the Athena table(s) might not be present.  The feature request is to ensure those CUR installation outside of CloudFormation are provided this same functionality.

**Comment by AjayTripathy** [comment]
This likely belongs in the community edition project more so than the open source, since maintenance of data sources is beyond the scope of the open core. 
What you want to do there is create a small utility that:
* Checks if Cloud Assets is enabled and there are assets from Athena. If so, start the utility.
* ~50h after the start of the month, issues a query to the Cloud Assets code
* If there is data for the previous month but no data for the new month, issue a MSCK REPAIR TABLE
 https://docs.aws.amazon.com/athena/latest/ug/msck-repair-table.html
* If there is still no data, issue an alert.

The time windowing functionality is similar to the way we fire alerts on intervals for kubecost, though the interval is monthly instead of daily. Reviewing the (closed source) code in https://github.com/kubecost/kubecost-cost-model/blob/develop/pkg/alerts/alert.go#L18 would be a great place to start.
