### ISSUE TITLE
aws pricing URL honors ETag

### ISSUE THREAD

**Issue by mdaniel** [kubecost/cost-model#15]
Since that file is currently over 600MB, it can be a very real win to use the `If-None-Match:` (or its `If-Modified-Since:` friend) to check if fetching those bytes could possibly result in any new information

Currently, since that URL is being served off of S3, it comes with all the expected headers, including `ETag:` containing the md5 of its contents:
```
	< Content-Length: 685820220
	< Last-Modified: Fri, 29 Mar 2019 04:08:55 GMT
	< ETag: "678d4f456aad44cb7a03708d7fd4511c"
```

If one sends that header back up, S3 is bright enough to indicate that downloading it will do you no good:
```
	> If-None-Match: "678d4f456aad44cb7a03708d7fd4511c"
	< HTTP/1.1 304 Not Modified
```

**Comment by AjayTripathy** [comment]
I think this is a good idea, but we do occasionally want to blow the cache when a new node joins the fleet, since even though the endpoint has no additional data for us

[RefreshPricingData](https://github.com/kubecost/cost-model/blob/master/main.go#L63) and this [block](https://github.com/kubecost/cost-model/blob/master/cloud/awsprovider.go#L287) both represent points at which this can happen. Maybe DownloadPricingData() can be modified to take an argument?

**Comment by AjayTripathy** [comment]
@mdaniel , I remember you saying that you had a partial solution here. Is still still something you would want to take? Happy to help/collaborate any way you would like.

**Comment by mdaniel** [comment]
I only have a "partial solution" in that I explored the per-region URLs and also confirmed that they do support ETag, but I didn't go so far as doing any Golang toward that end because it wasn't clear that switching was something that would be of general interest. It's even less of a burning fire now that the system no longer downloads that 600MB file over and over

**Comment by dwbrown2** [comment]
Cool, I propose we leave this open for now, especially while we still have #16 outstanding, but sounds like it's lower priority for the time being.

**Comment by kirbsauce** [comment]
Closing for now, as #16 has been done.  Please feel free to reopen if necessary.
