### ISSUE TITLE
ideally only download AWS pricing data for regions in use

### ISSUE THREAD

**Issue by mdaniel** [kubecost/cost-model#16]
The [Offer Index File](https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/reading-the-offer-index.html) has a `currentRegionIndexUrl` which then lists the per-region pricing data, in contrast to the 600MB+ [AmazonEC2 current json](https://github.com/kubecost/cost-model/blob/80c71ac6ee69d7ea8e476ead5b4ba41180f8cd45/cloud/awsprovider.go#L172)

If one were to only ask for regions used by the cluster, it would make downloading the data quicker

**Comment by dwbrown2** [comment]
I also support this based on everything I've seen. Several things to consider, which Matthew alludes to, are 1) a cluster may have assets in multiple regions and 2) the set of regions with assets provisioned _may_ change over time. 

One follow up question: since we will likely be streaming a much smaller amount of billing data with this approach, should our caching strategy change?

**Comment by AjayTripathy** [comment]
This has been done!
