### ISSUE TITLE
Helm chart - install without grafana and prometheus

### ISSUE THREAD

**Issue by botzill** [kubecost/cost-model#31]
Hi.

On our system, we have installed `prometheus-operator` and I would like to skip installing those. Are there any guides on installing without them? Do I need to install other thing related to Prometheus? Would be great to have some guide about it.

Thx a lot and great job!

**Comment by dwbrown2** [comment]
Hi @botzill, the main Kubecost application, which is a super set of this open source project, does indeed have the ability to ship without Prometheus & Grafana. 

There are a couple nuances to implementing this, partially because of recording rules that Kubecust uses to remain performant on larger clusters. Right now, we generally recommend getting up and running with the bundled install first and then we can help you make the transition to your own Prometheus and Grafana.

Happy to help you do this -- reach out to team@kubecost.com if you want to discuss further!

**Comment by luisdavim** [comment]
yeah, we also already have prometheus and grafana in all of our clusters and it seems like a waste to have an extra instance for this.

**Comment by kivagant-ba** [comment]
Can the app work without grafana and prometheus at all?

**Comment by dwbrown2** [comment]
@kivagant-ba do you mind sharing a bit more? 

The app can operate without Grafana today, although this limits some available views. It has a dependency on Prometheus though. Would you be looking to use a different database? We have discussed different integrations here so let me know what you're thinking!

**Comment by kivagant-ba** [comment]
I just don't have Prometheus since the company uses a third-party cloud monitoring system. That's why I'm curious if it's possible to use this very promising app without installing Prometheus.

**Comment by dwbrown2** [comment]
@kivagant-ba, not today. It does have Prometheus as a hard dependancy. We are actively exploring other integrations though -- reach out (team@kubecost.com) if you want chat in more detail!

As an alternative, you could install the bundled Prometheus and then export to your 3P monitoring system.

**Comment by botzill** [comment]
Hi @dwbrown2. Can you share a little bit about Prometheus dependencies and how we can take those configs and put in our custom Prometheus installation? From what I see here https://github.com/kubecost/cost-analyzer-helm-chart/blob/master/cost-analyzer/templates/cost-analyzer-config-map-template.yaml#L8 we can easily change the endpoint to our custom installation of prometheus and alertmanager. Now, the next question is: do you have some custom cofigs when it comes to promethus itself, like did you add smth new here: https://github.com/kubecost/cost-analyzer-helm-chart/blob/master/cost-analyzer/charts/prometheus/values.yaml#L852  or is the default one? If there is added smth new I can take that and put input my promethus. For grafana, I see that there are these dashboards defined: https://github.com/kubecost/cost-analyzer-helm-chart/blob/master/cost-analyzer/charts/grafana/values.yaml#L178. Grafana allows to create a config map with dashboards and it will read it automatically. I think this is a good solution here as well, this way we can easily separate dashboards from grafana itself and use custom installations. 


Hope this make sense :)

**Comment by dwbrown2** [comment]
@botzill close :) you would want to modify https://github.com/kubecost/cost-analyzer-helm-chart/blob/master/cost-analyzer/values.yaml 

I think it might be worth discussing before doing this in production. There are also recording rules and scrape configs that you need to pick up in order for this to perform properly on medium and large clusters.

Let's also plan to move continued conversation to https://github.com/kubecost/cost-analyzer-helm-chart since that's the relevant repo.

**Comment by dwbrown2** [comment]
New issue in Helm chart created: https://github.com/kubecost/cost-analyzer-helm-chart/issues/7

**Comment by dongy** [comment]
We already have prometheus and prometheus-node-exporter running in our cluster. Install kubecost brings prometheus-node-exporter as well which is always in Pending state, because its port has been occupied. Can I install kubecost without prometheus-node-exporter ?

**Comment by AjayTripathy** [comment]
You definitely can! Check out the kubecost helm chart https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/values.yaml#L583
