### ISSUE TITLE
More accurately track AWS spot prices

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-model#36]
Today the Kubecost project lets you supply a static, custom AWS spot price. Can we explore getting this information dynamically from AWS? There are at least two different options: 

1) **General spot pricing** -- some feed equivalent of the following to get general market data: https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-spot-price-history.html

2) **Specific spot pricing** -- feed for customer-specific prices:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-data-feeds.html

**Comment by AjayTripathy** [comment]
I don't think we need the firehose of data to accurately track spot pricing. Option 2 should be both more accurate and have easier data to work with, since the size will be much smaller (it only includes pricing data for spot instances you have, and arrives hourly).

The disadvantage of Option 2 is that we'll have to have some way for the user to add the bucket name of the feed-- perhaps it can be added to the aws.json file. Authentication could also come from the json file via service key, or be baked into the instance default credentials. It's not that hard to support both authentication strategies.

@mdaniel any additional thoughts here?

**Comment by dwbrown2** [comment]
I'm marking this as closed after the integration with Spot feed. Please feel free to reopen if needed.
